import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Bell, BookOpen, CalendarDays, ChevronLeft, ChevronRight, CreditCard, FileCheck2, GraduationCap, HelpCircle, Home, LayoutDashboard, LogOut, Settings, Users2, WalletCards } from "lucide-react";
import { useAuth } from "@/lib/AuthContext";
import { notificationsApi } from "@/api/services/notificationsApi";

const adminNav=[{label:"Dashboard",path:"/admin",icon:LayoutDashboard},{label:"Talabalar",path:"/admin/students",icon:GraduationCap},{label:"O'qituvchilar",path:"/admin/teachers",icon:Users2},{label:"Kurslar",path:"/admin/courses",icon:BookOpen},{label:"Guruhlar",path:"/admin/groups",icon:Users2},{label:"To'lovlar",path:"/admin/payments",icon:WalletCards},{label:"Xonalar",path:"/admin/rooms",icon:Home},{label:"Hisobotlar",path:"/admin/reports",icon:CalendarDays}];
const teacherNav=[{label:"Dashboard",path:"/teacher",icon:LayoutDashboard},{label:"Guruhlarim",path:"/teacher/groups",icon:Users2},{label:"Darslar",path:"/teacher/lessons",icon:BookOpen},{label:"Davomat",path:"/teacher/attendance",icon:CalendarDays},{label:"Uy vazifalari",path:"/teacher/homework",icon:FileCheck2},{label:"Imtihonlar",path:"/exams",icon:GraduationCap}];
const studentNav=[{label:"Dashboard",path:"/student",icon:LayoutDashboard},{label:"Guruhlarim",path:"/student/groups",icon:Users2},{label:"Dars jadvali",path:"/student/schedule",icon:CalendarDays},{label:"Uy vazifalari",path:"/student/homework",icon:FileCheck2},{label:"Imtihonlar",path:"/exams",icon:GraduationCap},{label:"To'lovlar",path:"/student/payments",icon:CreditCard}];
const system=[{label:"Profil",path:"/profile",icon:Users2},{label:"Bildirishnomalar",path:"/notifications",icon:Bell},{label:"Kutubxona",path:"/library",icon:BookOpen},{label:"Yordam markazi",path:"/help-center",icon:HelpCircle}];

export default function Sidebar({role="ADMIN",onNavigate,collapsed=false,onToggle}:{role?:string;onNavigate?:()=>void;collapsed?:boolean;onToggle?:()=>void}){
 const {logout}=useAuth(); const loc=useLocation(); const [unread,setUnread]=useState(0); const nav=role==="TEACHER"?teacherNav:role==="STUDENT"?studentNav:adminNav;
 useEffect(()=>{notificationsApi.list({limit:100}).then((r:any)=>setUnread((r?.items||[]).filter((x:any)=>!x.readAt).length)).catch(()=>setUnread(0))},[role,loc.pathname]);
 const item=(x:any)=><Link key={x.path} to={x.path} onClick={onNavigate} title={collapsed?x.label:undefined} className={`erp-side-item ${loc.pathname===x.path||loc.pathname.startsWith(x.path+"/")?"active":""} ${collapsed?"collapsed":""}`}><x.icon className="w-[18px] h-[18px]"/>{!collapsed&&<span>{x.label}</span>}{x.path==="/notifications"&&unread>0&&!collapsed&&<b>{unread>9?"9+":unread}</b>}</Link>;
 return <aside className={`erp-sidebar ${collapsed?"is-collapsed":""}`}><div className="erp-side-brand"><div className="erp-logo-mark">E</div>{!collapsed&&<div><strong>ERP</strong><small>EDUCATION CRM</small></div>}<button onClick={onToggle} className="erp-side-toggle">{collapsed?<ChevronRight/>:<ChevronLeft/>}</button></div><div className="erp-side-scroll"><p className="erp-side-label">Asosiy</p>{nav.map(item)}<p className="erp-side-label">Tizim</p>{system.map(item)}</div><div className="erp-side-bottom"><Link to="/settings" onClick={onNavigate} className={`erp-side-item ${collapsed?"collapsed":""}`}><Settings className="w-[18px] h-[18px]"/>{!collapsed&&<span>Sozlamalar</span>}</Link><button onClick={()=>logout(true)} className={`erp-side-item ${collapsed?"collapsed":""}`}><LogOut className="w-[18px] h-[18px]"/>{!collapsed&&<span>Chiqish</span>}</button></div></aside>
}
