import { useEffect, useRef, useState } from "react";
import { Bell, CheckCheck, ChevronDown, Menu, Search, ArrowRight, BookOpen, CalendarDays, WalletCards, GraduationCap } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import ThemeToggle from "@/components/ThemeToggle";
import { useAuth } from "@/lib/AuthContext";
import { notificationsApi, type AppNotification } from "@/api/services/notificationsApi";

const icons:any={PAYMENT:WalletCards,LESSON:CalendarDays,HOMEWORK:BookOpen,EXAM:GraduationCap,SYSTEM:Bell};
export default function Topbar({title,role="ADMIN",onMenuClick}:{title:string;subtitle?:string;role?:string;onMenuClick?:()=>void}){
 const {user}=useAuth(); const [open,setOpen]=useState(false),[profile,setProfile]=useState(false),[items,setItems]=useState<AppNotification[]>([]); const ref=useRef<HTMLDivElement>(null); const pref=useRef<HTMLDivElement>(null); const loc=useLocation();
 const load=()=>notificationsApi.list({limit:20}).then((r:any)=>setItems(r?.items||[])).catch(()=>{}); useEffect(()=>{void load()},[user?.id,loc.pathname]); useEffect(()=>{const fn=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false);if(pref.current&&!pref.current.contains(e.target as Node))setProfile(false)};document.addEventListener("mousedown",fn);return()=>document.removeEventListener("mousedown",fn)},[]);
 const unread=items.filter(x=>!x.readAt).length; const name=[user?.firstName,user?.lastName].filter(Boolean).join(" ")||"Foydalanuvchi"; const roleText=role==="TEACHER"?"O'qituvchi":role==="STUDENT"?"Talaba":"Administrator"; const initials=[user?.firstName?.[0],user?.lastName?.[0]].filter(Boolean).join("").toUpperCase()||"U";
 const markAll=async()=>{if(!unread)return;await notificationsApi.markAllRead();setItems(x=>x.map(n=>({...n,readAt:new Date().toISOString()})))}; const mark=async(id:number)=>{await notificationsApi.markRead(id);setItems(x=>x.map(n=>n.id===id?{...n,readAt:new Date().toISOString()}:n))};
 return <header className="erp-navbar"><div className="flex items-center gap-3"><button onClick={onMenuClick} className="erp-nav-menu lg:hidden"><Menu className="w-5 h-5"/></button><div><div className="erp-nav-kicker">EDUCATION CRM</div><div className="erp-nav-title">{title}</div></div></div><div className="erp-nav-search"><Search className="w-4 h-4"/><input placeholder="Qidirish..."/><kbd>⌘ K</kbd></div><div className="flex items-center gap-2"><ThemeToggle/><div ref={ref} className="relative"><button onClick={()=>setOpen(v=>!v)} className="erp-nav-icon"><Bell className="w-[19px] h-[19px]"/>{unread>0&&<span>{unread>9?"9+":unread}</span>}</button>{open&&<div className="erp-notification-popover"><div className="erp-notification-head"><div><h3>Bildirishnomalar</h3><p>{unread?`${unread} ta yangi xabar`:"Hammasi o'qilgan"}</p></div><button onClick={markAll} disabled={!unread}><CheckCheck className="w-4 h-4"/> O'qish</button></div><div className="erp-notification-list">{items.slice(0,6).map(n=>{const Icon=icons[n.type]||Bell;return <button key={n.id} onClick={()=>!n.readAt&&void mark(n.id)} className={`erp-notification-item ${!n.readAt?"unread":""}`}><span className="erp-notify-icon"><Icon className="w-4 h-4"/></span><span className="erp-notify-text"><strong>{n.title}</strong><small>{n.body}</small><em>{new Date(n.createdAt).toLocaleString("uz-UZ")}</em></span>{!n.readAt&&<i/>}</button>})}{!items.length&&<div className="erp-notification-empty">Bildirishnomalar yo'q</div>}</div><Link to="/notifications" onClick={()=>setOpen(false)} className="erp-notification-footer">Barcha xabarlar <ArrowRight className="w-4 h-4"/></Link></div>}</div><div ref={pref} className="relative"><button onClick={()=>setProfile(v=>!v)} className="erp-user-chip">{user?.photo?<img src={user.photo} alt=""/>:<span>{initials}</span>}<div className="hidden sm:block"><strong>{name}</strong><small>{roleText}</small></div><ChevronDown className="w-4 h-4 text-muted-foreground"/></button>{profile&&<div className="erp-profile-popover"><Link to="/profile">Profil</Link><Link to="/notifications">Bildirishnomalar</Link><Link to="/settings">Sozlamalar</Link></div>}</div></div></header>
}
