import type React from "react";
import { useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, FileCheck2, Plus, Send, Trash2, X } from "lucide-react";
import { useAuth } from "@/lib/AuthContext";
import { examsApi, type Exam } from "@/api/services/examsApi";
import { groupsApi } from "@/api/services/groupsApi";
import { studentsApi } from "@/api/services/studentsApi";

interface Student { id:number; user:{firstName:string;lastName:string} }
interface Result { id:number; studentId:number; attended:boolean; score:number|null; status:string; comment?:string|null; answerText?:string|null; answerFile?:string|null; submittedAt?:string|null; student:Student }

export default function Exams(){
 const {user}=useAuth(); const teacher=user?.role==="TEACHER"; const student=user?.role==="STUDENT";
 const [items,setItems]=useState<Exam[]>([]),[groups,setGroups]=useState<any[]>([]),[selected,setSelected]=useState<(Exam&{results:Result[]})|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[showCreate,setShowCreate]=useState(false),[showAnswer,setShowAnswer]=useState<(Exam&{results:Result[]})|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r:any=await examsApi.list({limit:100});setItems(r?.items||[]);if(teacher){const g:any=await groupsApi.list({limit:100});setGroups(g?.items||[])}}catch(e:any){setError(e?.message||"Imtihonlarni yuklab bo'lmadi")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[user?.id]);
 const open=async(e:Exam)=>{try{const r:any=await examsApi.get(e.id);setSelected(r)}catch(err:any){setError(err?.message||"Imtihon ochilmadi")}};
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{
  e.preventDefault();
  setSaving(true);
  setError("");
  try{
   const f=new FormData(e.currentTarget);
   const scheduledAtRaw=String(f.get("scheduledAt")||"");
   const endsAtRaw=String(f.get("endsAt")||"");
   const start=new Date(scheduledAtRaw);
   const end=new Date(endsAtRaw);
   if(!scheduledAtRaw||!endsAtRaw||Number.isNaN(start.getTime())||Number.isNaN(end.getTime())) throw new Error("Boshlanish va tugash vaqtini to‘g‘ri kiriting");
   if(end<=start) throw new Error("Tugash vaqti boshlanish vaqtidan keyin bo‘lishi kerak");
   const maxScore=Number(f.get("maxScore"));
   const passScore=Number(f.get("passScore"));
   if(passScore>maxScore) throw new Error("O‘tish bali maksimal balldan oshmasin");
   await examsApi.create({title:String(f.get("title")||"").trim(),groupId:Number(f.get("groupId")),scheduledAt:start.toISOString(),endsAt:end.toISOString(),maxScore,passScore,description:String(f.get("description")||"")});
   setShowCreate(false);
   setMessage("Imtihon yaratildi.");
   await load();
  }catch(e:any){
   console.error("Exam create error:",e);
   const detail=e?.data?.message;
   setError(Array.isArray(detail)?detail.join(", "):detail||e?.message||"Imtihon yaratilmadi");
  }finally{setSaving(false)}
 };
 const remove=async(id:number)=>{if(!confirm("Imtihonni o'chirishni tasdiqlaysizmi?"))return;try{await examsApi.remove(id);await load();setMessage("Imtihon o'chirildi.")}catch(e:any){setError(e?.message||"O'chirishda xatolik")}};
 const answer=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!showAnswer)return;setSaving(true);setError("");try{const f=new FormData(e.currentTarget);let answerFile:String|undefined;const file=f.get("file") as File|null;if(file?.size){const {uploadsApi}=await import("@/api/services/uploadsApi");answerFile=(await uploadsApi.file(file)).url}await examsApi.answer(showAnswer.id,String(f.get("answerText")||""),answerFile as string|undefined);setShowAnswer(null);setMessage("Imtihon javobi yuborildi.");await load()}catch(e:any){setError(e?.message||"Javob yuborilmadi")}finally{setSaving(false)}};
 const saveResults=async()=>{if(!selected)return;setSaving(true);try{await examsApi.submitResults(selected.id,selected.results.map(r=>({studentId:r.studentId,attended:r.attended,score:r.attended&&r.score!==null?r.score:undefined,comment:r.comment||undefined})));setMessage("Imtihon natijalari saqlandi.");setSelected(null);await load()}catch(e:any){setError(e?.message||"Natijalar saqlanmadi")}finally{setSaving(false)}};
 const rows=useMemo(()=>items,[items]);
 return <div className="space-y-6"><div className="erp-page-banner"><div className="erp-banner-icon"><FileCheck2 className="w-7 h-7"/></div><div className="erp-banner-copy"><h2 className="erp-page-title">Imtihonlar</h2><p className="erp-page-subtitle">{teacher?"Imtihon yaratish, natija kiritish va talabalarni baholash":"Imtihonlarni ko'rish va javob topshirish"}</p></div>{teacher&&<button onClick={()=>setShowCreate(true)} className="ml-auto h-11 px-4 rounded-xl accent-gradient text-white font-bold inline-flex gap-2 items-center"><Plus className="w-4 h-4"/>Imtihon yaratish</button>}</div>
 {message&&<div className="p-3 rounded-xl bg-emerald-50 text-emerald-700 border border-emerald-200 flex justify-between text-sm"><span>{message}</span><button onClick={()=>setMessage("")}><X className="w-4 h-4"/></button></div>}{error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 border border-red-200">{error}</div>}
 {loading?<div className="py-20 text-center text-muted-foreground">Yuklanmoqda...</div>:<div className="erp-table-shell"><div className="erp-table-scroll"><table className="w-full min-w-[900px] text-sm"><thead><tr className="bg-[#f4f8f4] text-left text-muted-foreground"><th className="px-5 py-4">Imtihon</th><th className="px-5 py-4">Guruh</th><th className="px-5 py-4">Sana</th><th className="px-5 py-4">Ball</th><th className="px-5 py-4">Holat</th><th className="px-5 py-4 text-right">Amal</th></tr></thead><tbody>{rows.map(e=>{const own:any=(e as any).results?.[0];return <tr key={e.id} className="border-t border-border hover:bg-muted/20"><td className="px-5 py-4 font-bold">{e.title}<div className="text-xs text-muted-foreground mt-1">{e.description||""}</div></td><td className="px-5 py-4">{e.group?.name||"—"}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1"><CalendarClock className="w-4 h-4"/>{new Date(e.scheduledAt).toLocaleString("uz-UZ")}</span></td><td className="px-5 py-4">{student?(own?.score!=null?`${own.score} / ${(e as any).maxScore}`:"—"):((e as any)._count?.results??0)+" ta"}</td><td className="px-5 py-4"><span className="px-2.5 py-1 rounded-full bg-primary/10 text-primary font-bold text-xs">{own?.status||e.status}</span></td><td className="px-5 py-4 text-right space-x-2">{student&&<button onClick={async()=>{const r:any=await examsApi.get(e.id);setShowAnswer(r)}} className="px-3 py-2 rounded-lg bg-primary text-primary-foreground font-bold"><Send className="w-4 h-4 inline mr-1"/>Javob</button>}{teacher&&<button onClick={()=>void open(e)} className="px-3 py-2 rounded-lg border font-bold">Natijalar</button>}{teacher&&<button onClick={()=>void remove(e.id)} className="p-2 rounded-lg border text-red-600"><Trash2 className="w-4 h-4"/></button>}</td></tr>})}</tbody></table>{!rows.length&&<div className="p-12 text-center text-muted-foreground">Imtihonlar mavjud emas.</div>}</div></div>}
 {showCreate&&<Modal title="Yangi imtihon" onClose={()=>setShowCreate(false)}><form onSubmit={create} className="space-y-4"><Field label="Nomi"><input name="title" required className="erp-form-control"/></Field><Field label="Guruh"><select name="groupId" required className="erp-form-control"><option value="">Tanlang</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Boshlanish"><input name="scheduledAt" type="datetime-local" required className="erp-form-control"/></Field><Field label="Tugash"><input name="endsAt" type="datetime-local" required className="erp-form-control"/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Maksimal ball"><input name="maxScore" type="number" min="1" defaultValue="100" required className="erp-form-control"/></Field><Field label="O'tish bali"><input name="passScore" type="number" min="0" defaultValue="60" required className="erp-form-control"/></Field></div><Field label="Izoh"><textarea name="description" className="erp-form-control min-h-24"/></Field><button disabled={saving} className="w-full h-11 rounded-xl accent-gradient text-white font-bold">{saving?"Saqlanmoqda...":"Imtihon yaratish"}</button></form></Modal>}
 {showAnswer&&<Modal title={`Javob topshirish — ${showAnswer.title}`} onClose={()=>setShowAnswer(null)}><div className="mb-4 p-3 rounded-xl bg-muted/40 text-sm">Boshlanish: {new Date(showAnswer.scheduledAt).toLocaleString("uz-UZ")}<br/>Tugash: {showAnswer.endsAt?new Date(showAnswer.endsAt).toLocaleString("uz-UZ"):"Belgilanmagan"}</div><form onSubmit={answer} className="space-y-4"><Field label="Javob"><textarea name="answerText" className="erp-form-control min-h-40" placeholder="Javobingiz..."/></Field><Field label="Fayl"><input name="file" type="file" className="erp-form-control"/></Field><button disabled={saving} className="w-full h-11 rounded-xl accent-gradient text-white font-bold">{saving?"Yuborilmoqda...":"Javobni yuborish"}</button></form></Modal>}
 {selected&&<Modal title={`Natijalar — ${selected.title}`} onClose={()=>setSelected(null)} wide><div className="space-y-3 max-h-[60vh] overflow-auto">{selected.results.map((r,i)=><div key={r.id||r.studentId} className="grid grid-cols-[1fr_110px_130px] gap-3 items-center border rounded-xl p-3"><div><b>{r.student.user.firstName} {r.student.user.lastName}</b>{r.answerText&&<p className="text-xs text-muted-foreground mt-1 line-clamp-2">{r.answerText}</p>}{r.answerFile&&<a href={r.answerFile} target="_blank" rel="noreferrer" className="text-xs text-primary">Faylni ochish</a>}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={r.attended} onChange={e=>setSelected(s=>s?{...s,results:s.results.map((x,j)=>j===i?{...x,attended:e.target.checked}:x)}:s)}/> Keldi</label><input className="erp-form-control" type="number" min="0" max={(selected as any).maxScore} value={r.score??""} onChange={e=>setSelected(s=>s?{...s,results:s.results.map((x,j)=>j===i?{...x,score:e.target.value===""?null:Number(e.target.value)}:x)}:s)} placeholder="Ball"/></div>)}{!selected.results.length&&<div className="p-8 text-center text-muted-foreground">Natijalar hali yo'q.</div>}</div><button onClick={saveResults} disabled={saving} className="w-full mt-4 h-11 rounded-xl accent-gradient text-white font-bold">{saving?"Saqlanmoqda...":"Natijalarni saqlash"}</button></Modal>}
 </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-1.5"><span className="text-sm font-semibold">{label}</span>{children}</label>}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="fixed inset-0 z-[100] bg-black/45 flex items-center justify-center p-4"><div className={`bg-white rounded-2xl shadow-2xl w-full ${wide?"max-w-4xl":"max-w-xl"} max-h-[90vh] overflow-auto`}><div className="flex justify-between items-center p-5 border-b"><h3 className="text-lg font-extrabold">{title}</h3><button onClick={onClose} className="p-2 rounded-lg hover:bg-muted"><X className="w-5 h-5"/></button></div><div className="p-5">{children}</div></div></div>}
